from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

from dotenv import dotenv_values


ROOT = Path(__file__).resolve().parents[1]
LOCAL_DIR = ROOT / ".local" / "app"
UPLOAD_DIR = LOCAL_DIR / "uploads"
OUTPUT_DIR = LOCAL_DIR / "outputs"
PREVIEW_DIR = LOCAL_DIR / "previews"
JOB_DIR = LOCAL_DIR / "jobs"
MASTER_STATE_DIR = LOCAL_DIR / "master-state"
MASTER_TEMP_DIR = LOCAL_DIR / "master-temp"
LOCAL_PERSON_JOB_DIR = LOCAL_DIR / "local-person-jobs"
LOCAL_PERSON_OUTPUT_DIR = LOCAL_DIR / "local-person-outputs"
MODEL_DIR = LOCAL_DIR / "models"
BENCHMARK_DIR = LOCAL_DIR / "benchmark"
COMPARISON_DIR = LOCAL_DIR / "comparison"
PROMPT_COMPARISON_DIR = LOCAL_DIR / "prompt-comparison"
COST_LEDGER_PATH = LOCAL_DIR / "cost-ledger.jsonl"
COST_OUTCOME_PATH = LOCAL_DIR / "cost-outcomes.json"
STATIC_DIR = ROOT / "static"
SAFE_COVER_DIR = STATIC_DIR / "assets" / "safe-covers"
AVATAR_ASSET_DIR = ROOT / "assets" / "avatar_families"
POSE_AVATAR_PLAYGROUND_DIR = LOCAL_DIR / "pose-avatar-p1"

# These bundled covers are deterministic geometric placeholders generated by
# scripts/generate_public_placeholders.py. They contain no third-party artwork.
SAFE_COVERS = {
    "bald-bearded": "几何遮罩 1",
    "graduate": "几何遮罩 2",
    "architect": "几何遮罩 3",
    "office": "几何遮罩 4",
    "programmer": "几何遮罩 5",
    "blue-collar": "几何遮罩 6",
}

for directory in (UPLOAD_DIR, OUTPUT_DIR, PREVIEW_DIR, JOB_DIR, MASTER_STATE_DIR, MASTER_TEMP_DIR, LOCAL_PERSON_JOB_DIR, LOCAL_PERSON_OUTPUT_DIR, MODEL_DIR, BENCHMARK_DIR, COMPARISON_DIR, PROMPT_COMPARISON_DIR):
    directory.mkdir(parents=True, exist_ok=True)


def _load_env() -> dict[str, str]:
    values = {key: value for key, value in dotenv_values(ROOT / ".env.local").items() if value}
    values.update({key: value for key, value in os.environ.items() if value})
    return values


ENV = _load_env()
PUBLIC_MODE = ENV.get("SCENE_FIRST_PUBLIC_MODE", "").strip().lower() in {"1", "true", "yes", "on"}
LOCAL_MASTER_ENABLED = ENV.get("SCENE_FIRST_LOCAL_MASTER", "").strip().lower() in {"1", "true", "yes", "on"}
POSE_AVATAR_OVERLAY_ENABLED = ENV.get("SCENE_FIRST_POSE_AVATAR_OVERLAY", "").strip().lower() in {"1", "true", "yes", "on"}


# Only image-to-image endpoints with reviewed request schemas belong here.  The
# catalog is deliberately not an arbitrary endpoint text field: each entry has
# to be compatible with local crop upload and local mask compositing.
FAL_EDIT_MODELS = {
    "fal-ai/nano-banana-pro/edit": {
        "label": "Nano Banana Pro",
        "adapter": "nano_banana",
        "description": "Google 图像编辑；当前默认路线。",
    },
    "openai/gpt-image-2/edit": {
        "label": "GPT Image 2（经 fal）",
        "adapter": "gpt_image",
        "description": "OpenAI 图像编辑；支持向模型传入编辑掩码。",
    },
    "fal-ai/bytedance/seedream/v4.5/edit": {
        "label": "字节 Seedream 4.5（经 fal）",
        "adapter": "seedream",
        "description": "字节图像编辑；局部范围由本机裁剪和合成保证。",
    },
    "fal-ai/bytedance/seedream/v5/lite/edit": {
        "label": "字节 Seedream 5 Lite（经 fal）",
        "adapter": "seedream",
        "description": "字节较快的图像编辑路线；局部范围由本机裁剪和合成保证。",
    },
}


def fal_model_label(model: str) -> str:
    profile = FAL_EDIT_MODELS.get(model)
    return f"fal.ai · {profile['label']}" if profile else "fal.ai · 未验证编辑模型"


@dataclass(frozen=True)
class ProviderSettings:
    name: str
    label: str
    key_name: str | None
    model: str
    estimated_cny: float
    supports_mask: bool = False

    @property
    def configured(self) -> bool:
        return self.key_name is None or bool(ENV.get(self.key_name))


PROVIDER_SETTINGS = {
    "local": ProviderSettings("local", "本地原创插画", None, "local-illustration-v1", 0.0, True),
    "openai": ProviderSettings(
        "openai", "GPT Image 2", "OPENAI_API_KEY", ENV.get("OPENAI_IMAGE_MODEL", "gpt-image-2"),
        float(ENV.get("OPENAI_ESTIMATED_CNY", "0")), True,
    ),
    "gemini": ProviderSettings(
        "gemini", "Gemini Image", "GEMINI_API_KEY",
        ENV.get("GEMINI_IMAGE_MODEL", "gemini-3.1-flash-image"),
        float(ENV.get("GEMINI_ESTIMATED_CNY", "0")), False,
    ),
    "fal": ProviderSettings(
        "fal", fal_model_label(ENV.get("FAL_IMAGE_MODEL", "fal-ai/nano-banana-pro/edit")), "FAL_KEY",
        ENV.get("FAL_IMAGE_MODEL", "fal-ai/nano-banana-pro/edit"),
        float(ENV.get("FAL_ESTIMATED_CNY", "0")), True,
    ),
    "ark": ProviderSettings(
        "ark", "火山方舟 · Seedream 5 Lite", "ARK_API_KEY",
        ENV.get("ARK_IMAGE_MODEL", "doubao-seedream-5.0-lite"),
        float(ENV.get("ARK_ESTIMATED_CNY", "0")), False,
    ),
    "bfl": ProviderSettings(
        "bfl", "FLUX.2", "BFL_API_KEY", ENV.get("BFL_IMAGE_MODEL", "flux-2-pro"),
        float(ENV.get("BFL_ESTIMATED_CNY", "0")), False,
    ),
    "qwen": ProviderSettings(
        "qwen", "Qwen Image 2.0", "DASHSCOPE_API_KEY",
        ENV.get("QWEN_IMAGE_MODEL", "qwen-image-2.0"),
        float(ENV.get("QWEN_ESTIMATED_CNY", "0")), False,
    ),
}

ARK_IMAGE_BASE_URL = ENV.get(
    "ARK_IMAGE_BASE_URL", "https://ark.cn-beijing.volces.com/api/plan/v3/images/generations"
)

MAX_UPLOAD_BYTES = 30 * 1024 * 1024
MAX_IMAGE_PIXELS = int(ENV.get("MAX_IMAGE_PIXELS", "16000000"))
MAX_DETECTION_PIXELS = int(ENV.get("MAX_DETECTION_PIXELS", "3200000"))
DETECTION_TILE_MIN_EDGE = int(ENV.get("DETECTION_TILE_MIN_EDGE", "1450"))
DETECTION_ENABLE_TILES = ENV.get("DETECTION_ENABLE_TILES", "1").strip().lower() in {"1", "true", "yes", "on"}
LOW_CONFIDENCE_THRESHOLD = 0.55
# Per-photo limit for cloud edits.  It deliberately does not increase the
# number of photos being processed by this local prototype.
MAX_PARALLEL_PERSON_EDITS = int(ENV.get("MAX_PARALLEL_PERSON_EDITS", "2"))
YUNET_MODEL_URL = (
    "https://huggingface.co/opencv/face_detection_yunet/resolve/main/"
    "face_detection_yunet_2023mar.onnx?download=true"
)
YUNET_MODEL_PATH = MODEL_DIR / "face_detection_yunet_2023mar.onnx"
PERSON_MODEL_URL = (
    "https://huggingface.co/opencv/person_detection_mediapipe/resolve/main/"
    "person_detection_mediapipe_2023mar.onnx?download=true"
)
PERSON_MODEL_PATH = MODEL_DIR / "person_detection_mediapipe_2023mar.onnx"
