const fs = require('fs');
const path = require('path');
const { chromium } = require('playwright');

(async () => {
  const root = path.resolve(__dirname, '..');
  const uploadDir = path.join(root, '.local', 'app', 'uploads');
  const files = fs.existsSync(uploadDir) ? fs.readdirSync(uploadDir).filter(file => file.endsWith('.png')) : [];
  if (!files.length) throw new Error('请先运行 npm run app:test，以创建本地 QA 图片。');
  const input = path.join(uploadDir, files[0]);
  const outDir = path.join(root, '.local', 'app');
  const edge = 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe';
  const launchOptions = {headless: true};
  if (fs.existsSync(edge)) launchOptions.executablePath = edge;
  const browser = await chromium.launch(launchOptions);
  const page = await browser.newPage({viewport: {width: 1440, height: 1000}, deviceScaleFactor: 1});
  await page.goto('http://127.0.0.1:8765', {waitUntil: 'networkidle'});
  await page.setInputFiles('#fileInput', input);
  await page.waitForSelector('#editorCanvas:not(.hidden)');
  await page.click('#openPreCrop');
  await page.waitForSelector('#cropSheet:not(.hidden)');
  await page.click('[data-ratio="0.8"]');
  await page.click('#applyCrop');
  await page.waitForSelector('#cropSheet', {state: 'hidden'});
  await page.click('#detectButton');
  await page.waitForFunction(() => document.querySelector('#editorCanvas').dataset.scale);
  await page.waitForFunction(() => document.querySelector('#countLabel').textContent.includes('共'));
  await page.selectOption('#provider', 'local');
  await page.click('#clearAll');
  await page.click('#manualBox');
  await page.locator('#editorCanvas').evaluate(canvas => {
    const box = canvas.getBoundingClientRect();
    const point = (name, x, y) => canvas.dispatchEvent(new PointerEvent(name, {
      bubbles: true, pointerId: 1, clientX: box.left + box.width * x, clientY: box.top + box.height * y,
    }));
    point('pointerdown', 0.38, 0.16);
    point('pointerup', 0.63, 0.78);
  });
  await page.waitForFunction(() => document.querySelector('#countLabel').textContent.startsWith('1 人'));
  const zoomBefore = await page.locator('#editorCanvas').evaluate(canvas => canvas.width);
  const touchSession = await page.context().newCDPSession(page);
  const box = await page.locator('#editorCanvas').boundingBox();
  const point = (id, x, y) => ({id, x: box.x + box.width * x, y: box.y + box.height * y, radiusX: 1, radiusY: 1, force: 1});
  await touchSession.send('Input.dispatchTouchEvent', {type: 'touchStart', touchPoints: [point(1, .35, .45)]});
  await touchSession.send('Input.dispatchTouchEvent', {type: 'touchStart', touchPoints: [point(1, .35, .45), point(2, .65, .55)]});
  await touchSession.send('Input.dispatchTouchEvent', {type: 'touchMove', touchPoints: [point(1, .35, .45), point(2, .91, .74)]});
  await touchSession.send('Input.dispatchTouchEvent', {type: 'touchEnd', touchPoints: []});
  const zoomAfter = await page.locator('#editorCanvas').evaluate(canvas => canvas.width);
  if (zoomAfter <= zoomBefore) throw new Error(`检测后的照片无法双指放大（before=${zoomBefore}, after=${zoomAfter}, zoom=${await page.locator('#editorCanvas').getAttribute('data-zoom')}）。`);
  await page.screenshot({path: path.join(outDir, 'qa-editor.png'), fullPage: true});
  await page.click('#processButton');
  await page.waitForSelector('#resultSection:not(.hidden)', {timeout: 30000});
  const summary = await page.textContent('#resultSummary');
  if (!summary.includes('场景与服装保持原像素')) throw new Error(`缺少像素保真结果：${summary}`);
  await page.click('#openResultCrop');
  await page.waitForSelector('#cropSheet:not(.hidden)');
  await page.click('[data-ratio="1"]');
  await page.click('#applyCrop');
  await page.waitForSelector('#cropSheet', {state: 'hidden'});
  if (!(await page.textContent('#resultSummary')).includes('已应用导出裁剪')) throw new Error('成品裁剪没有生效。');
  const cropDownload = page.waitForEvent('download');
  await page.click('#downloadPng');
  await cropDownload;
  await page.screenshot({path: path.join(outDir, 'qa-result.png'), fullPage: true});
  const mobile = await browser.newPage({viewport: {width: 390, height: 844}, deviceScaleFactor: 1});
  await mobile.goto('http://127.0.0.1:8765/?lab=0', {waitUntil: 'networkidle'});
  if (await mobile.locator('nav .lab-only:visible').count()) throw new Error('公开模式仍显示实验室入口。');
  const manifest = await mobile.evaluate(async () => fetch(document.querySelector('link[rel=manifest]').href).then(response => response.json()));
  if (manifest.display !== 'standalone' || manifest.icons.length < 2) throw new Error('PWA manifest 配置不完整。');
  await mobile.evaluate(() => navigator.serviceWorker.ready.then(registration => Boolean(registration.active)));
  await mobile.screenshot({path: path.join(outDir, 'qa-mobile-initial.png'), fullPage: true});
  await mobile.setInputFiles('#fileInput', input);
  await mobile.waitForSelector('#editorCanvas:not(.hidden)');
  await mobile.click('#mobileSecondary');
  await mobile.waitForSelector('#cropSheet:not(.hidden)');
  await mobile.screenshot({path: path.join(outDir, 'qa-mobile-crop-editor.png'), fullPage: true});
  await mobile.click('#rotateCrop');
  await mobile.click('#applyCrop');
  await mobile.screenshot({path: path.join(outDir, 'qa-mobile-crop.png'), fullPage: true});
  await mobile.close();
  console.log(summary);
  await page.goto('http://127.0.0.1:8765/preflight', {waitUntil: 'networkidle'});
  await page.waitForFunction(() => document.querySelector('#preflightCanvas').dataset.scale);
  const progress = await page.textContent('#progress');
  if (!progress.includes('/20')) throw new Error(`预审样本数不正确：${progress}`);
  await page.screenshot({path: path.join(outDir, 'qa-preflight.png'), fullPage: true});
  await page.goto('http://127.0.0.1:8765/review', {waitUntil: 'domcontentloaded'});
  await page.waitForFunction(() => document.querySelectorAll('.review-card').length === 20);
  const reviewText = await page.textContent('#reviewRoot');
  if (/GPT Image|Gemini|FLUX|Qwen|本地原创/.test(reviewText)) throw new Error('盲测页泄露了模型名称。');
  await page.waitForFunction(() => [...document.querySelectorAll('.review-card:first-of-type img')].every(image => image.complete && image.naturalWidth > 0), null, {timeout: 60000});
  await page.screenshot({path: path.join(outDir, 'qa-review.png'), fullPage: false});
  await page.goto('http://127.0.0.1:8765/settings', {waitUntil: 'networkidle'});
  await page.waitForFunction(() => document.querySelectorAll('.provider-card').length === 6);
  const secretInputs = await page.locator('input[type=password]').count();
  if (secretInputs !== 6) throw new Error(`API 设置页密钥输入数量不正确：${secretInputs}`);
  await page.screenshot({path: path.join(outDir, 'qa-settings.png'), fullPage: true});
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
